export const userActionTypes = Object.freeze({
  AUTH_AUTO_SIGN_IN: 'AUTH_AUTO_SIGN_IN',
  AUTH_USER: 'AUTH_USER',
  AUTH_USER_SUCCESS: 'AUTH_USER_SUCCESS',
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS',
  DELETE_USER: 'DELETE_USER',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  CHANGE_USER_ROLE: 'CHANGE_USER_ROLE',
  CHANGE_USER_ROLE_SUCCESS: 'CHANGE_USER_ROLE_SUCCESS'
});

export const uiActionTypes = Object.freeze({
  START_ACTION: 'START_ACTION',
  STOP_ACTION: 'STOP_ACTION',
  REFRESH_ACTION_START: 'REFRESH_ACTION_START',
  REFRESH_ACTION_STOP: 'REFRESH_ACTION_STOP',
  TOGGLE_POPUP_MESSAGE: 'TOGGLE_POPUP_MESSAGE',
  ADD_ERROR_ACTION: 'ADD_ERROR_ACTION',
  CLEAR_ERROR_ACTIONS: 'CLEAR_ERROR_ACTIONS'
});

export const timezoneActionTypes = Object.freeze({
  ADD_NEW_TIMEZONE_ENTRY: 'ADD_NEW_TIMEZONE_ENTRY',
  ADD_NEW_TIMEZONE_ENTRY_SUCCESS: 'ADD_NEW_TIMEZONE_ENTRY_SUCCESS',
  UPDATE_TIMEZONE_ENTRY: 'UPDATE_TIMEZONE_ENTRY',
  UPDATE_TIMEZONE_ENTRY_SUCCESS: 'UPDATE_TIMEZONE_ENTRY_SUCCESS',
  DELETE_TIMEZONE_ENTRY: 'DELETE_TIMEZONE_ENTRY',
  DELETE_TIMEZONE_ENTRY_SUCCESS: 'DELETE_TIMEZONE_ENTRY_SUCCESS',
  FETCH_TIMEZONE_ENTRIES: 'FETCH_TIMEZONE_ENTRIES',
  FETCH_TIMEZONE_ENTRIES_SUCCESS: 'FETCH_TIMEZONE_ENTRIES_SUCCESS'
});

export const searchActionTypes = Object.freeze({
  SEARCH_TIMEZONE_ENTRIES: 'SEARCH_TIMEZONE_ENTRIES',
  SEARCH_TIMEZONE_ENTRIES_SUCCESS: 'SEARCH_TIMEZONE_ENTRIES_SUCCESS',
  SEARCH_USERS: 'SEARCH_USERS',
  SEARCH_USERS_SUCCESS: 'SEARCH_USERS_SUCCESS',
  CLEAR_SEARCH: 'CLEAR_SEARCH'
});
