export enum eScreenNames {
    CLOCK = 'CLOCK',
    ADD_NEW_TIMEZONE = 'ADD_NEW_TIMEZONE',
    TIMEZONE_EDIT = 'TIMEZONE_EDIT',
    SEARCH = 'SEARCH',
    AUTH = 'AUTH',
    AUTH_LOADING = 'AUTH_LOADING',
    AUTH_EDIT = 'AUTH_EDIT'
}

export enum eStackNames {
    APP_STACK = 'APP_STACK',
    CLOCK_STACK = 'CLOCK_STACK',
    CLOCK_STACK_WITH_DRAWER = 'CLOCK_STACK_WITH_DRAWER',
    AUTH_STACK = 'AUTH_STACK',
    AUTH_LOADING_STACK = 'AUTH_LOADING_STACK'
}